# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aaron Do
tagline:          'My Website'
description:      ''
domain:           Melancholy22.github.io
url:              https://melancholy22.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  resumeBlocks:
    order:
      - introduction.md
      - experience.md
      - projects.md
    
